### PR TITLE
Add debugging tutorial

### PR DESCRIPTION
**Pull request by iluetkeb**
I've spent some time figuring out how to get proper debugging support for NuttX, and it wasn't as trivial as I had expected, so I thought that a tutorial on this might help others as well.

### CODE REVIEW

**Comment by imuguruza** [comment]
I think this tutorial should be placed in an "advanced" section. I'm fine with adding it and afterwards we could rearrange the sections

**Comment by iluetkeb** [comment]
> I think this tutorial should be placed in an "advanced" section. I'm fine with adding it and afterwards we could rearrange the sections

Why do you think it is advanced?

**Comment by iluetkeb** [comment]
Nevermind. I agree that this is not first thing one will do, so it's not basic in that sense. I'll put it in an "Intermediate" section, however, because I think that after you've got the basic stuff done, debugging is fairly high on the list of capabilities that people will need.

**Comment by imuguruza** [comment]
Well, as we discussed in the webpage meeting, the first tutorials should be something easy that you could make with your laptop: i.e. running a Docker file that contains micro-ROS example, an Agent and Client exchanging data.

Next step should be providing, again, Dockers we already produced that contains precompiled micro-ROS NuttX examples where you could use it with an micro-ROS Agent running in a computer and exchanging data among them.

We could add some client library examples in between...

And finally, the embedded stuff, where we explain people how to use/code NuttX. 

I believe we agreed on trying to erase entry barrier to the technology

**Comment by imuguruza** [comment]
As said, even that, we could rearrange the content later

**Comment by iluetkeb** [comment]
> Well, as we discussed in the webpage meeting, the first tutorials should be something easy that you could make with your laptop: i.e. running a Docker file that contains micro-ROS example, an Agent and Client exchanging data.
> Next step should be providing, again, Dockers we already produced that contains precompiled micro-ROS NuttX examples where you could use it with an micro-ROS Agent running in a computer and exchanging data among them.
> 
> We could add some client library examples in between...

Totally. Only, I would categorize all of that as "Basic". 
 
> And finally, the embedded stuff, where we explain people how to use/code NuttX.

I agree that this shouldn't be the first thing, but wouldn't you say that classifying it as "Advanced" would be a bit odd, given that our whole project is about putting stuff on embedded devices? While not the first thing to do, it shouldn't be the last either.

What I would classify as "Advanced" or maybe even "Expert" is stuff like writing a driver for NuttX.

> I believe we agreed on trying to erase entry barrier to the technology

Totally agreed. But, I'm not responsible for the fact that my, admittedly not basic, tutorial is currently the first thing to receive a PR ;-) Both you and @BorjaOuterelo have many existing tutorials which would be more appropriate for the basic level. Please add them!

btw, I will not merge my tutorial right now, but give you more time to add your content, before we add something like this.

**Comment by adamdbrw** [comment]
We can start by classifying it as Intermediate and then see what kind of scope of tutorials we actually have and where this one fits. It is easy to move pages around.

**Comment by imuguruza** [comment]
> I tend to agree, it is a advanced tutorial from my point of view. But apart from that I would merge it soon.

Same here

**Comment by iluetkeb** [comment]
Yesterday I noticed that the tutorial does not work out-of-the-box on Ubuntu 18.04. The reason are 1) compile problems with the openocd-nuttx branch (due to stricter compiler checking) and 2) arm-none-eabi-gdb no longer exists.

**Pull request merged**
